### ISSUE TITLE
Crash on ChannelIo.boot method

### ISSUE THREAD

**Issue by dhatuna** [zoyi/channel-plugin-ios#60]
An unknown crash occurred on following codes:

        let settings = ChannelPluginSettings()
        settings.pluginKey = "(plugin key)"
        settings.userId = "(a user id)"

        let profile = Profile()
        profile.set(name: UserData.data.name)

        ChannelIO.boot(with:settings, profile: profile)

Plus, I copied debug messages on debugger below. Please give any advice to solve this problem

2020-01-21 18:27:59.772286+0900 Pickle[4590:1547472] -[GUL_Pickle.AppDelegate-2130E81C-F1C6-4A1F-85D5-B9C703C9A653 window]: unrecognized selector sent to instance 0x281f54cd0
2020-01-21 18:27:59.772534+0900 Pickle[4590:1547472] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GUL_Pickle.AppDelegate-2130E81C-F1C6-4A1F-85D5-B9C703C9A653 window]: unrecognized selector sent to instance 0x281f54cd0'
*** First throw call stack:
(0x1bb30aa48 0x1bb031fa4 0x1bb20e5a8 0x1bf3ab86c 0x1bb30e86c 0x1bb310a7c 0x1066c840c 0x1bb02dc38 0x1bb03342c 0x1bb033ba8 0x1bb04050c 0x1bb02e3fc 0x1066d0e90 0x10735183c 0x10736f16c 0x1074c74ec 0x10734e738 0x10992d7fc 0x10992ebd8 0x10993cc34 0x1bb2885e4 0x1bb2835d8 0x1bb282adc 0x1c5208328 0x1bf37dae0 0x10531e230 0x1bb10c360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by intoxicated** [comment]
Thank you for reporting the issue. Please provide following information to resolve your issue.

1. SDK version
2. Identify "instance 0x281f54cd0" ? what type of instance is this?
3. iOS version 
4. Device or simulator version

**Comment by intoxicated** [comment]
I also suspect to look into [GUL_Pickle.AppDelegate-2130E81C-F1C6-4A1F-85D5-B9C703C9A653 window] this message. You can actually identify what instance get caused to crash by adding exception breaking point.

**Comment by dhatuna** [comment]
Hi, Thanks for reply.

First, I running my project on following conditions :

1. iOS development target in Xcode : 11.0
2. Device : iPhone X
3. iOS version on the device : 13.3
4. SDK version : ChannelIO 6.1.17
5. Using SwiftUI and SceneDelegate

And, i tried to look up details about the issue, but I cannot find more details cause it happens in the SDK.
I've only found that it crashed on the function named “prepare” on ChannelIO+Helper.swift file.

FYI, At the first moment, when I found this error, I thought it failed to find correct (keyed) UIWindow instance of the application. (Not sure)

Well, any advice will be a huge help for us.

Many thanks.

Best regards 
JK

**Comment by intoxicated** [comment]
How did you install the SDK? if you use cocoapods, you still can see the source code hence you can actually pin point the crash with adding exception break. On the other hand, can you update your SDK version to latest version and see if it still happens?

**Comment by dhatuna** [comment]
Hi, I installed it via Cocoapods.

And the crash occurred on line 36 of CRToastManager.m :

+ (void)setDefaultOptions:(NSDictionary*)defaultOptions {
    [CRToast setDefaultOptions:defaultOptions];
}

Thank you
JK

**Comment by intoxicated** [comment]
If the code you mentioned causes the problem, can you comment out line 48 in ChannelIO+helper.swift where it initialized the toast by `CRToastManager.setDefaultOptions(toastOptions)` and see if the problem still occurs?

**Comment by dhatuna** [comment]
Hi, sorry for late reply.

I did what you asked, but it still crashed :(

**Comment by intoxicated** [comment]
Did you try to install latest version? I can't reproduce your crash on my side :/

**Comment by intoxicated** [comment]
close for now due to no response for a while
